# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'Ubuntu-16.04'
  # cancelTimeoutInMinutes: 5

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
    echo "ok1"
    sleep 10000
    echo "ok2"
  displayName: 'Run a multi-line script'
  timeoutInMinutes: 30 # CHECKME
