# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

jobs:
  - job: MyJob
    # fetchDepth:1
    displayName: My First Job
    # workspace:
    #   clean: outputs

    cancelTimeoutInMinutes: 1
    timeoutInMinutes: 1 # CHECKME

    strategy:
      matrix:
        linux:
          imageName: 'ubuntu-16.04'
        mac:
          imageName: 'macos-10.13'

    pool:
      vmImage: $(imageName)
      # vmImage: 'Ubuntu-16.04'
      # BUG: these are accepted in this context but have no effect
      # cancelTimeoutInMinutes: 1
      # timeoutInMinutes: 1 # CHECKME

    steps:
    - script: echo Hello, world!
      displayName: 'Run a one-line script'

    - script: |
        set -e
        echo "v1"
        echo Add other tasks to build, test, and deploy your project.
        echo See https://aka.ms/yaml
        echo "ok1"
        git log | cat
        sleep 240
        echo "ok2"
      displayName: 'Run a multi-line script'
      # timeoutInMinutes: 1 # ok, that works; check whether works w > 60?
