# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  - master # disable CI build for branch except master
# pr:
#   - master # only kick off for pr targeting master

jobs:
  - job: MyJob
    displayName: My First Job
    # workspace:
    #   clean: outputs

    cancelTimeoutInMinutes: 1
    timeoutInMinutes: 1

    strategy:
      matrix:
        linux:
          imageName: 'ubuntu-16.04'
        mac:
          imageName: 'macos-10.13'

    pool:
      vmImage: $(imageName)
      # vmImage: 'Ubuntu-16.04'
      # BUG: `timeoutInMinutes` accepted under pool but has no effect

    steps:
    - checkout: self # self represents the repo where the initial Pipelines YAML file was found
      fetchDepth: 1  # the depth of commits to ask Git to fetch
      # TODO: git clone --single-branch --branch tag
    # - template: azure-pipelines/linux/continuous-build-linux.yml

    - script: echo Hello, world!
      displayName: 'Run a one-line script'

    - script: |
        enabled: false
        set -e
        echo "v1"
        echo Add other tasks to build, test, and deploy your project.
        echo See https://aka.ms/yaml
        echo "ok1"
        git log | cat
        # sleep 240
        echo "ok2"
      displayName: 'Run a multi-line script'
      # timeoutInMinutes: 1 # ok, that works; check whether works w > 60?
